name: Review

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run build
        run:  stack build
      - name: Run tests
        run:  stack test

